// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

namespace Ultra.Sampler;

public static class UltraSamplerConstants
{
    public const string ProviderName = "Ultra-Sampler";

    public const string ProviderGuidString = "d0b3f179-3b34-50ad-4c32-dd48a98dc5bf"; // This Guid is generated by the EventSource - Got it via EventSource.GetGuid(typeof(UltraSamplerSource))

    public static readonly Guid ProviderGuid = new(ProviderGuidString);

    public const int NativeCallStackEventId = 1;

    public const int NativeModuleEventId = 2;

    public const int TaskNativeCallStackEventId = 1;

    public const int TaskNativeModuleEventId = 2;
}